"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 0]
show_hidden = true
sort_by = "natural"
linemode = "size"

[input]
cursor_blink = true

[opener]
edit = [
  { run = '${EDITOR:=hx} "$@"', desc = "$EDITOR", block = true },
]
